[WIP] Yatopia 2 Electric Boogaloo [Yatopia Reforged]
tr7zw/YAPFA pull request #339
Opened 2021-01-18 00:03 UTC by duplexsystem

This PR cleans up the mess that is our legacy code base by doing the following:
- Use Gradle and Toothpick for base build system
- Redo Yatopia's build system to be more dynamic, cleaner, and based in kotlin
- Include all of Purpur's patches
- Additional items not yet implemented

2021-01-18 20:35 UTC, Titaniumtown submitted a review, later dismissed
LGTM

2021-01-18 21:00 UTC, toinouH submitted a review, later dismissed
This system seems less complicated than the other one.

2021-01-18 21:08 UTC, HookWoods commented
toothpick is really faster compared to the actual system, and you only have to compile the upstream dir on the first upstream or when you upstream. So really fast to apply patches, even for CI Server. Also, the new implementation for the sidestream looks pretty nice and works well. Maybe need one day to just found a fix for windows computer about the bash cmd that is not always recognized by IntelliJ but is by git bash. wp

2021-01-18 21:11 UTC, HookWoods approved these changes, later dismissed
Yes

2021-01-18 21:12 UTC, Titaniumtown submitted a review, later dismissed
yes

2021-01-18 21:20 UTC, toinouH reviewed
I understand if you want to leave it; we can do ir later too but it's confusing.

2021-01-18 21:20 UTC, toinouH commented on README.md
>  You can find a full explanation of the Yatopia configuration file on the [wiki](https://github.com/YatopiaMC/Yatopia/wiki). Check out the list of patches included in this project and who created them
Remove infos about recommended configs; we can re-ade it later.
```suggestion
 You can find a full explanation of the Yatopia configuration file on the [wiki](https://github.com/YatopiaMC/Yatopia/wiki). Check out the list of patches included in this project and who created them [here](PATCHES.md).
```

2021-01-18 21:24 UTC, Titaniumtown approved these changes, later dismissed
review #3 lol

Edit: crap I referenced an issue xD

2021-01-18 21:32 UTC, PhantomGaming27229 submitted a review, later dismissed
its an improvement to the build system etc, approving

2021-01-18 21:36 UTC, toinouH submitted a review, later dismissed
Ready

2021-01-18 21:38 UTC, HookWoods approved these changes, later dismissed

2021-01-19 05:46 UTC, MrIvanPlays requested changes, later dismissed
flying squids patch is present.
remove that

2021-01-19 05:53 UTC, Titaniumtown commented
@MrIvanPlays why would the flying squids patch prevent the merging of this PR? :confused:

2021-01-19 05:56 UTC, MrIvanPlays commented
> @MrIvanPlays why would the flying squids patch prevent the merging of this PR? 😕

because flying squids are not gonna get into yatopia.
never ever ever ever

2021-01-19 05:56 UTC, Titaniumtown commented
why

2021-01-19 06:00 UTC, Titaniumtown commented
Stop acting like a child. If you don't want flying squids, you can disable it in `purpur.yml`, other than that it doesn't affect you. That is in no way a valid reason to block the merging of this PR.

2021-01-19 06:10 UTC, MrIvanPlays commented
> Stop acting like a child. If you don't want flying squids, you can disable it in `purpur.yml`, other than that it doesn't affect you. That is in no way a valid reason to block the merging of this PR. If you have an actual reason on why this new build system shouldn't be merged, feel free to tell us.

i have but ive dealt with it . if you dont like what im thinking then go somewhere else. I dont want the flying squids patch in yatopia, mainly cuz of historical reasons.

2021-01-19 06:11 UTC, MrIvanPlays commented
also @duplexsystem if im not wrong purpur had a patch where it reverted the revert of mc-4 fix, blacklist that too

2021-01-19 06:12 UTC, Titaniumtown commented
> i have but ive dealt with it . if you dont like what im thinking then go somewhere else. I dont want the flying squids patch in yatopia, mainly cuz of historical reasons.

Keyword **YOU** don't want it in yatopia, yatopia is not your project. And those "historical reasons" are stupid af.

2021-01-19 06:14 UTC, Titaniumtown commented
> if you dont like what im thinking then go somewhere else

Everyone but you approves of this PR, it's the opposite situation here, you're in the minority. It's ***you*** who doesn't like what everyone else is thinking, not me or anyone else here.

2021-01-19 06:17 UTC, MrIvanPlays commented
you can stop arguing you won't win.

2021-01-19 06:20 UTC, Titaniumtown commented
If you have an actual reason as to not merging this PR, fell free to tell us. But as of now you can stop with this childish behavior.

2021-01-19 06:22 UTC, Titaniumtown commented
Why did you request a review from me. lmfao

2021-01-19 06:24 UTC, Titaniumtown approved these changes, later dismissed
lmfao, Ivan dismissed my review

2021-01-19 06:25 UTC, Titaniumtown commented
> not a review team.

what? lmao

2021-01-19 06:25 UTC, Titaniumtown commented
How am I not a part of the review team?

2021-01-19 06:28 UTC, MrIvanPlays commented
> How am I not a part of the review team?

you're not removed from the org yet but you're not gonna have the perms you currently have.

2021-01-19 06:28 UTC, Titaniumtown commented
I am a part of the org. And the only reason why I don't have the `review team` rank on the discord server is because you had a temper tantrum after I got it.

2021-01-19 06:29 UTC, MrIvanPlays requested changes, later dismissed
blacklist flying squids and revert of revert of mc-4 fix
update the submodules

2021-01-19 06:30 UTC, toinouH commented
Ok guys stop.
Ivan make a proper review, only that matters: duplex will do the job for squids
Jettison: I know you strongly disagree his point of view but let him work.

2021-01-19 06:30 UTC, MrIvanPlays commented
> I am a part of the org. And the only reason why I don't have the `review team` rank on the discord server is because you had a temper tantrum after I got it.

![image](https://img.mrivanplays.com/DiscordCanary_zYZwTM6MQT.png)

2021-01-19 06:36 UTC, Titaniumtown commented
m8, you blurred like half the convo lmfao.

2021-01-19 06:37 UTC, MrIvanPlays commented
> m8, you blurred like half the convo lmfao.

ofc i did, you will otherwise start arguing even more

2021-01-19 19:46 UTC, duplexsystem commented
Ready for Merge.

2021-01-19 19:47 UTC, Titaniumtown approved these changes, later dismissed
LGTM

2021-01-19 19:49 UTC, krolik-exe submitted a review, later dismissed

2021-01-20 02:42 UTC, BillyGalbreath commented
![](https://cdn.discordapp.com/attachments/697248751575761057/801278308608114738/unknown.png)

Funny, cause this system was designed exactly _for_ [Purpur](https://github.com/pl3xgaming/Purpur/pull/122). Why you trying to pass this off as your own?

2021-01-20 02:47 UTC, duplexsystem commented
![Screenshot from 2021-01-19 20-46-57](https://user-images.githubusercontent.com/25417900/105120243-7e45d780-5a97-11eb-9c98-8f4ee21b96c1.png)
nope by my build system I just mean my the part that deals with other fork's patches

2021-01-20 02:49 UTC, duplexsystem commented
also your forget it's not 100% your build system to being with you could say your taking toothpick and passing it off as your own right now I know you didn't mean it like that :)

2021-01-20 02:49 UTC, duplexsystem commented
hope that clears things up @BillyGalbreath

2021-01-20 02:52 UTC, BillyGalbreath commented
> also your forget it's not 100% your build system to being with you could say your taking toothpick and passing it off as your own right now I know you didn't mean it like that :)

We never claimed it was ours. We gave proper attribution, and even talked to both mikro _and_ mini while in the process of building it. You are flat out claiming it's yours, and even going as far as to say we could use it from you.. This is DMCA territory.

2021-01-20 02:55 UTC, notOM3GA commented
> my build system would be useful for purpur

purpur already has this lol

2021-01-20 02:56 UTC, duplexsystem commented
> I just mean my the part that deals with other fork's patches

if you want more attribution please ask :)

2021-01-20 02:59 UTC, duplexsystem commented
> This is DMCA territory.
As far as I'm aware it's not because it's under MIT and you never included a Purpur or P3lx specific copyright notice in your licence but again if you wish for more attribution I can give you it.

2021-01-20 03:05 UTC, duplexsystem commented
@BillyGalbreath just so you know if you would like more attribution before merge now is the time to ask because we're merging soon.

2021-01-20 03:06 UTC, PaulBGD commented
> > This is DMCA territory.
> 
> As far as I'm aware it's not because it's under MIT and you never included a Purpur or Pl3x specific copyright notice in your licence but again if you wish for more attribution I can give you it.

MIT doesn't give away the copyright, the original authors still own it. MIT just opens up some of these permissions so you can use it, not claim the copyright as your own.

2021-01-20 03:12 UTC, duplexsystem commented
@PaulBGD I was just saying Purpur's licence does not have `(C) 2021 Pl3xgaming` or something so it's still being distributed under and MIT and this is still under MIT (so It should be compliment with the `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.` clause), but regardless It was never my intention to claim all of toothpick as my own, just the fraction that I wrote and I'm willing to prove credit where ever @BillyGalbreath thinks is necessary.

2021-01-20 03:36 UTC, BillyGalbreath commented
> Purpur's licence does not have `(C) 2021 Pl3xgaming` or something so it's still being distributed under and MIT and this is still under MIT (so It should be compliment with the `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.` clause)

I suggest you read [Title 17 of the Copyright Law](https://www.copyright.gov/title17/title17.pdf) sections 401(a), 401(d), and 504(c)(2).

2021-01-20 03:48 UTC, duplexsystem commented
I'm not here to have a legal battle. Do you want credit anywhere or do you want it taken down or neither? I've stated before I'm willing to work if you if you really care.

2021-01-20 05:10 UTC, Titaniumtown approved these changes, later dismissed
LGTM, lets get this merged!!

2021-01-20 05:39 UTC, MrIvanPlays commented
@BillyGalbreath @PaulBGD you have a point here, it's really not our system, it's a heavily modified toothpick to fit our needs. 
we still license it mit so i dont think there should be any issues with the license ( not a lawyer or something, but its the same license so whats the problem? )

2021-01-20 07:11 UTC, gabboman commented
Im going to make my own fork with no dramas!



Fuck I had a discussion with myself I just failed.

2021-01-20 07:32 UTC, MrIvanPlays requested changes, later dismissed
Upstream commit message is not how it should be.
![!](https://img.mrivanplays.com/WindowsTerminal_bpsR47a6bE.png)
Paper and Purpur should be separated by a `/`.

There's literally NO way to resolve conflicting sidestream patches without messing up the rebuilt patches. EVERY known way of editing commits doesn't work ( they work only for our patches and not sidestream patches ). I don't know how will you fix this but if you can't find a fix this system gets scrapped.

Not sure if it is related, but I get dependency resolve problems whilst using IntelliJ.

2021-01-20 20:37 UTC, Titaniumtown requested changes, later dismissed
the version in `0002-Brandings.patch` should be fixed

2021-01-20 20:37 UTC, Titaniumtown commented on patches/server/0002-Brandings.patch
> ++    private static final String GITHUB_BRANCH_NAME = "ver/1.16.4";
uh oh, that shouldn't happen.

2021-01-20 20:38 UTC, Titaniumtown commented on patches/server/0002-Brandings.patch
> ++    private static final String GITHUB_BRANCH_NAME = "ver/1.16.4";
I'll fix it myself rq.

2021-01-20 22:24 UTC, Titaniumtown approved these changes, later dismissed
LGTM

2021-01-21 05:43 UTC, Titaniumtown approved these changes, later dismissed

2021-01-21 06:02 UTC, Titaniumtown submitted a review, later dismissed
Now it should be read for merging.

2021-01-21 06:29 UTC, MrIvanPlays approved these changes, later dismissed

2021-01-21 06:32 UTC, MrIvanPlays commented
waiting on codemc to retrigger the build so i can merge

2021-01-21 10:49 UTC, MrIvanPlays approved these changes

2021-01-21 10:54 UTC, toinouH approved these changes
@MrIvanPlays

2021-01-21 10:55 UTC, epserv approved these changes

2021-01-21 10:58 UTC, merged