New async nbt cache
tr7zw/YAPFA pull request #347
Opened 2021-01-21 17:00 UTC by HookWoods

The goal of this pr is to reduce I/O operations from the main thread while saving player data and also to avoid too many I/O operations while reading NBT Player file by using a cache (Which start to delete the oldest data when there is too much player compared to the map size)
I don't know if the map implementation is the best method or using a LRU system would be better

2021-01-21 17:02 UTC, Titaniumtown commented on patches/server/0066-New-nbt-cache.patch
> +
Maybe put a description about what the patch does in the patch comments here.

2021-01-21 17:03 UTC, MrIvanPlays requested changes
yet again _I_ have to make the patch to a level...

2021-01-21 17:04 UTC, Titaniumtown commented
> yet again _I_ have to make the patch to a level...

what?

2021-01-21 17:05 UTC, MrIvanPlays commented
> > yet again _I_ have to make the patch to a level...
> 
> what?

there are diff problems, missing `// Yatopia` comments, unmarked imports...
I thought hugo would watch me do it on his other 2 prs but looks like he hasn't learned so I'd have to make it _yet again_

2021-01-21 17:06 UTC, Titaniumtown commented
Ah ok. I didn't understand what you meant lmao.

2021-01-21 17:10 UTC, Titaniumtown requested changes
LGTM, just needs that info in the patch commits, and proper commits when you change a section of code (as @MrIvanPlays said). But either than that, since it's been in a production environment, I see no reason as to why it shouldn't get merged!

2021-01-23 22:51 UTC, Titaniumtown approved these changes
Along with @HookWoods using this patch privately in production for a while, I've been using it for the past 2 days on my server without any issues whatsoever. Seems good to merge with `dev/ver/1.16.5`

2021-01-24 04:30 UTC, ishland submitted a review, later dismissed
Seems good to me but there are still some small issues.

2021-01-24 04:30 UTC, ishland commented on patches/server/0069-New-nbt-cache.patch
> ++        this.worldNBTStorage.executorService.shutdown();
// Yatopia

2021-01-24 04:30 UTC, ishland commented on patches/server/0069-New-nbt-cache.patch
> +-            NBTCompressedStreamTools.a(nbttagcompound, file);
Always comment out deleted code

2021-01-24 04:30 UTC, ishland commented on patches/server/0069-New-nbt-cache.patch
> +-            if ( org.bukkit.Bukkit.getOnlineMode() && !normalFile ) // Paper - Check online mode first // Akarin - ensures normal file
Always comment out deleted code

2021-01-24 04:30 UTC, ishland commented on patches/server/0069-New-nbt-cache.patch
> +-            if (normalFile) { // Akarin - avoid double I/O operation
Always comment out deleted code

2021-01-24 04:31 UTC, ishland commented on patches/server/0069-New-nbt-cache.patch
> ++import org.yatopiamc.yatopia.server.cache.NBTCache;
Don't use imports

2021-01-25 16:32 UTC, Titaniumtown approved these changes
LGTM. I addressed @ishland and my own requests.

2021-01-25 16:37 UTC, merged