Threaded WorldGen
tr7zw/YAPFA pull request #375
Opened 2021-01-29 03:07 UTC by ishland

Continuation of #333 

## This feature is currently in testing, please report any bugs here

## This branch currently do the following things
- Utilizes WorldGen thread pools better
- Make feature generation off-thread
- Multi-threaded RegionFile IO with literally 0 blocking

2021-01-29 17:04 UTC, Titaniumtown submitted a review, later dismissed
I personally haven't had any issues with these patches at all so far, they've worked wonders. But more testing is probably needed.

2021-02-16 19:06 UTC, toinouH requested changes

2021-02-16 19:06 UTC, toinouH commented on patches/server/0068-lithium-MultiNoiseBiomeSourceMixin.patch
> +
```suggestion
This code was originally made by SuperCoder7979 in lithium https://github.com/CaffeineMC/lithium-fabric/
This code was orignally licensed under the LGPL-3.0 license.

```

2021-04-23 00:10 UTC, Titaniumtown commented
Superseded by #471

2021-04-23 00:10 UTC, closed without merging